mongo:
    databaseName: tramsOperations
    url: ${MONGODB_URI:mongodb://tramsOperations:myTraMSpassword@localhost:27017/tramsOperations}
spring:
    application:
        name: trams-operations
    profiles:
        active: dev-test
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
storage:
    location: src/main/resources/upload-dir

server:
    port: 8084
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

train:
    inspection:
        period: 8

tram:
    inspection:
        period: 9
