mongo:
  databaseName: tramsBusiness
  url: mongodb://tramsBusiness:myTraMSpassword@localhost:27017/tramsBusiness
spring:
  application:
    name: trams-business
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true