mongo:
  databaseName: tramsCrm
  url: mongodb://tramsCrm:myTraMSpassword@localhost:27017/tramsCrm
spring:
  application:
    name: trams-crm
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true