mongo:
  databaseName: trams
  url: ${MONGODB_URI:mongodb://trams:myTraMSpassword@localhost:27017/trams}
spring:
  application:
    name: trams-server
  profiles:
        active: dev-test
  servlet:
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
storage:
    location: src/main/resources/upload-dir

server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#Length of authentification tokens
token:
  length: 10

#Auto-logout after how many minutes
logout:
  minutes: 30

train:
    inspection:
        period: 8

tram:
    inspection:
        period: 9