#Comment
version: '3.7'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mymongodb
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mymongodb

  trams-operations:
    image: daveajlee/trams-operations:master
    container_name: trams-operations
    restart: always
    depends_on:
      - mongo
    ports:
      - 8084:8084
    environment:
      EUREKA_URI: http://host.docker.internal:8761/eureka
      MONGODB_URI: mongodb://tramsOperations:myTraMSpassword@host.docker.internal:27017/tramsOperations

  trams-business:
    image: daveajlee/trams-business
    container_name: trams-business
    restart: always
    depends_on:
      - mongo
      - eureka
    ports:
      - 8083:8083
    environment:
      EUREKA_URI: http://host.docker.internal:8761/eureka
      MONGODB_URI: mongodb://tramsBusiness:myTraMSpassword@host.docker.internal:27017/tramsBusiness

  trams-crm:
    image: daveajlee/trams-crm:master
    container_name: trams-crm
    restart: always
    depends_on:
      - mongo
    ports:
      - 8082:8082
    environment:
      EUREKA_URI: http://host.docker.internal:8761/eureka
      MONGODB_URI: mongodb://tramsCrm:myTraMSpassword@host.docker.internal:27017/tramsCrm

  personalman:
    image: daveajlee/personalman
    container_name: personalman
    restart: always
    depends_on:
      - mongo
    ports:
      - 8150:8150
    environment:
      EUREKA_URI: http://host.docker.internal:8761/eureka
      MONGODB_URI: mongodb://personalman:myPMpassword@host.docker.internal:27017/personalman

  eureka:
    image: daveajlee/eureka-server
    container_name: eureka
    restart: always
    ports:
      - 8761:8761

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf