# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for TraMS Server

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
  pull_request:
    branches: [ main ]
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        server-id: github
        server-username: GITHUB_USER_REF
        server-password: GITHUB_TOKEN_REF
    - name: Build with Maven
      run: mvn -B -Pgithub package --file server/pom.xml
      env:
        GITHUB_USER_REF: ${{secrets.GH_PACKAGE_REPO_USERNAME}}
        GITHUB_TOKEN_REF: ${{secrets.GH_PACKAGE_REPO_PASSWORD}}
